[package]
name = "software-security-homework"
version = "0.1.0"
authors = ["luojia65"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
